### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by gretio** [YoniCalsin/cb-valid#1]
Hi, I hope you help me, I have this problem.

`
const res = cbValid(val, expts)
TypeError: cbValid is not a function
    at Object.<anonymous> (D:\si.js:10:13)
?[90m    at Module._compile (internal/modules/cjs/loader.js:776:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:643:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m
`

My code is:

`const cbValid = require("cb-valid")

const val = "gretio"
const expts = [
   {
      name: "isEmail",
      message: "Email is invalid!"
   }
]
const res = cbValid(val, expts)
console.log(res);`

**Comment by YoniCalsin** [comment]
Hi friend.! the default attribute is missing, since it is ES5, in versions higher than ES5 at the time the default attribute is not necessary!

Add the default value :) this way: 

> default

`const cbValid = require("cb-valid").default`

I hope I solved your problem!

**Comment by gretio** [comment]
Problem solved! :)

Thanks @YoniCalsin.
You are a crack!
